[package]
name = "spipes"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.61"
tonic = "0.11.0"
tokio = { version = "1.37.0", features = ["full"] }
prost = "0.12.6"

[build-dependencies]
tonic-build = "0.11.0"
